theme: jekyll-theme-slate
title: Welcome to kerrsr1's ePortfolio
description: This page will showcase artifacts from my computer science degree program at Southern New Hampshire University which will demonstrate core concepts learned throughout the program.
